---
- name: Dynamic CIS Task Filter
  hosts: all
  become: true
  gather_facts: false
  vars:
    # Adding trim filter here to catch any accidental spaces in the input string
    audit_result: []

  tasks:
    - debug:
        msg: "{{inventory_hostname}}"

    - name: remove special meaning for . in selection
      ansible.builtin.set_fact:
        selections: "{{ (index | string).replace(' ', '').split(',') | list }}"
    
    - debug: var=selection

    - name: Load the master index list
      include_vars:
        file: rhel9_cis.yml

    - name: include cis role
      ansible.builtin.include_tasks: actions.yaml
      loop: "{{ selections }}"
      loop_control:
        loop_var: selection

    - debug: var=all_results
