---
- name: Dynamic CIS Task Filter
  hosts: all
  become: true
  gather_facts: false
  vars:
    # Adding trim filter here to catch any accidental spaces in the input string
    audit_result: []

  tasks:
    - debug:
        msg: "{{inventory_hostname}}"

    - name: remove special meaning for . in selection
      ansible.builtin.set_fact:
        selections: "{{ index.replace(' ', '').split(',') | list }}"
    
    - debug: var=selection

    - name: Load the master index list
      include_vars:
        file: rhel9_cis.yml

    - name: include cis role
      ansible.builtin.include_tasks: actions.yaml
      loop: "{{ selections }}"
      loop_control:
        loop_var: selection

    - debug: var=all_results
#    - fail:
#
#    - name:  trigger verificaiton task when selction ends with '.' - substring match
#      block:
#        - name: remove special meaning for . in selection
#          ansible.builtin.set_fact:
#            filter_str: "^{{ selection.replace('.', '\\.') }}"
#    
#        - name: trigger the CIS action for list of policies
#          #ansible.builtin.include_tasks: actions.yaml
#          debug: var=item
#          loop: "{{ rhel9_cis.keys() | select('match', filter_str) | list }}"
#          loop_control:
#            loop_var: cis_item
#      when:
#      - selection is match("^([0-9]|\\.)+\\.$")
#    
#
#    - name:  trigger verificaiton task when selction exactly match
#      block:
#        - name: trigger the CIS action for single policies
#          ansible.builtin.include_tasks: actions.yaml
#          vars:
#            cis_item: "{{ selection }}"
#      when:
#      - selection in cis_rules.keys()|list
#
#
#    - name: Process input and filter indexes
#      set_fact:
#        # Using | from YAML to keep it as a list and stripping whitespace inside the loop
#        filtered_indexes: >-
#          {% set final_list = [] -%}
#          {% set input_list = index.replace(' ', '').split(',') -%}
#          {% for query in input_list -%}
#            {% if query.endswith('.') -%}
#              {% for idx in rhel9_cis -%}
#                {% set id = idx.id -%}
#                {% if id.startswith(query) -%}
#                  {% set _ = final_list.append(idx) -%}
#                {% endif -%}
#              {% endfor -%}
#            {% elif query | length > 0 -%}
#              {% if query ==  -%}
#                {% set _ = final_list.append(query.strip()) -%}
#              {% endif -%}
#            {% endif -%}
#          {% endfor -%}
#          {{ final_list | unique }}
#
#    - name: Convert filtered indexes to file paths
#      set_fact:
#        audit_task_playbook: "{{ filtered_indexes | map('replace', '.', '_') | map('regex_replace', '^(.*)$', 'cis_rhel9_audit_tasks/cis_audit_\\1.yml') | list }}"
#        audit_result_var: "{{ filtered_indexes | map('replace', '.', '_') | map('regex_replace', '^(.*)$', 'status_\\1') | list }}"
#
#    - name: Show final task list
#      debug:
#        var: audit_task_playbook
#
#    - name: Show final var list
#      debug:
#        var: audit_result_var
#
#    #- name: Create /usr/local/bin/cis directory
#    #  ansible.builtin.file:
#    #    path: /usr/local/bin/cis
#    #    state: directory
#    #    owner: root
#    #    group: root
#    #    mode: '0755'
#
#    - name: Trigger the audit tasks
#      include_tasks: "{{ item }}"
#      ignore_errors: yes
#      loop: "{{ audit_task_playbook | list }}"
#      loop_control:
#        label: "Running: {{ item }}"
#
#    - name: Show final result
#      debug:
#        var: audit_result
#
#    - name: Save audit result to a JSON file
#      copy:
#        content: "{{ cis_result | to_nice_json }}"
#        dest: "./{{inventory_hostname}}_audit_result.json"
#      delegate_to: localhost
